Repository Malawi-DCCMS/weather-app, pull requests merged in 2024-08, with the labels that each got.

#214 207 add region to location search
  README.md
  assets/geonames-unique.ts
  assets/geonames.json
  assets/geonames.ts
  get_geonames.py
  src/common/constants.common.ts
  src/components/Search.tsx
  src/lib/autocomplete/index.d.ts
  src/lib/cap-client/rss.ts
  src/screens/main.screen.tsx
  src/screens/search.screen.tsx
  src/services/geonames.service.ts
  src/store/alert.slice.ts
  src/store/location.slice.ts
  src/types/index.d.ts
  src/utils/places.ts
Labels: enhancement

#215 chore(app): bump to version 1.1.0
  android/app/build.gradle
Labels: documentation

#216 fix(swipe-down): unwrap from useCallback
  src/screens/main.screen.tsx
Labels: bug
